version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
    - "3000:3000"
    env_file: ./api-gateway/.env
    depends_on:
    - redis
    environment:
    - REDIS_URL=REDIS_URL=redis://localhost:6379

  identity-service:
    build: ./identity-service
    env_file: ./identity-service/.env
    ports:
    - "3002:3002"
    depends_on:
    - redis
    environment:
    - REDIS_URL=REDIS_URL=redis://localhost:6379
  payment-service:
    build: ./payment-service
    env_file: ./payment-service/.env
    ports:
    - "3001:3001"
    depends_on:
    - redis
    environment:
    - REDIS_URL=REDIS_URL=redis://localhost:6379

  platform-services:
    build: ./platform-services
    env_file: ./platform-services/.env
    ports:
    - "3003:3003"
    depends_on:
    - redis
    environment:
    - REDIS_URL=REDIS_URL=redis://localhost:6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"