services:
 api_gateway:
  build: ./api-gateway
  ports:
   - "3000:3000"
  env_file: ./api-gateway/.env
  depends_on:
   - redis
  environment:
    - REDIS_URL=redis://redis:6379
 identity-service:
  build: ./identity-service
  ports:
   - "3002:3002"
  env_file: ./identity-service/.env
  depends_on:
   - redis
  environment:
    - REDIS_URL=redis://redis:6379
 payment-service:
  build: ./payment-service
  ports:
   - "3001:3001"
  env_file: ./payment-service/.env
  depends_on:
   - redis
  environment:
    - REDIS_URL=redis://redis:6379
 platform-services:
  build: ./platform-services
  ports:
   - "3003:3003"
  env_file: ./platform-services/.env
  depends_on:
   - redis
  environment:
    - REDIS_URL=redis://redis:6379
 redis:
  image: redis:alpine
  ports:
   - "6379:6379"
 